baseurl = "/"
title = "Web is more"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'We are, two developpers Full-stack localize in Basse-Normandie in Flers and Saint-lô<br />
                <!--[-->We create a web site.<!--]-->'
  logo = "fa-wikipedia-w"
  copyright = "Untitled"



[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.fr]
languageName = "Français"
weight = 2
title = "Web-is-more"
description = '<!--[-->Nous sommes deux developpeurs Full-stack situés en Basse-Normandie à Flers et à Saint-Lö.<br />
                <!--[-->Nous créons des sites web.<!--]-->'
